### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by emilylordahl** [keji96/BlackJack#2]
Great job Kevin! Nicely documented `readme`. I like how you figured out how to build the cards with CSS and JS. Really nice. You could even mess around with the `transform` property in CSS to have the letters flip around on each card. http://www.w3schools.com/cssref/css3_pr_transform.asp

See below for suggestion: 

``` js
var displayCard = $('<div>').addClass("card");
```

And in your CSS:

``` css
.card {
    background: black;
    borderColor: #808080 #000000 #000000 #80808;
    borderWidth: 2px;
    border-style: solid;
    color: white;
    fontSize: 20pt;
    position: absolute;
    width: 3.75em;
    height: 5.00em;
    left: 8.0em;
    bottom: 0.375em;
}
```

Think about how you can use inputs and click events to get the bet from the user instead of prompts. Maybe you can use some elements on the DOM that hold data values to track bets? 

Otherwise, really nice work!
